package executord

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// DefaultTokenFileName is the file auto-generated tokens are persisted to,
// relative to the data directory.
const DefaultTokenFileName = "token.txt"

// TokenSource identifies where an effective shared secret came from. The
// secret itself is never logged; only the source is safe to display.
type TokenSource string

const (
	// TokenSourceExplicit is a --token value passed on the command line.
	TokenSourceExplicit TokenSource = "command line"
	// TokenSourceEnv is the NEUROPIPE_EXECUTOR_TOKEN environment variable.
	TokenSourceEnv TokenSource = "environment"
	// TokenSourceConfiguredFile is the token file named in the boot config.
	TokenSourceConfiguredFile TokenSource = "configured token file"
	// TokenSourceSaved is a previously generated token in the data directory.
	TokenSourceSaved TokenSource = "saved token file"
)

// ResolvedToken describes the effective shared secret. Value must never be
// logged; Path and Source are safe for display.
type ResolvedToken struct {
	Value     string
	Source    TokenSource
	Path      string
	Generated bool
}

// dataRoot normalises the configured data directory.
func dataRoot(boot BootConfig) string {
	if strings.TrimSpace(boot.DataDir) == "" {
		return "data"
	}
	return boot.DataDir
}

// savedTokenPath is where auto-generated tokens live by default.
func savedTokenPath(boot BootConfig) string {
	return filepath.Join(dataRoot(boot), DefaultTokenFileName)
}

// ResolveToken determines the effective shared secret without ever creating
// one. Precedence: explicit --token, environment, configured token file, and
// finally a token generated by an earlier run. An empty result means no
// token is configured yet.
func ResolveToken(boot BootConfig, explicit string) (ResolvedToken, error) {
	if token := strings.TrimSpace(explicit); token != "" {
		return ResolvedToken{Value: token, Source: TokenSourceExplicit}, nil
	}
	if token := strings.TrimSpace(os.Getenv(TokenEnvVar)); token != "" {
		return ResolvedToken{Value: token, Source: TokenSourceEnv}, nil
	}
	if path := strings.TrimSpace(boot.TokenFile); path != "" {
		data, err := os.ReadFile(path)
		if err != nil {
			return ResolvedToken{}, fmt.Errorf("read configured token file %q: %w", path, err)
		}
		if token := strings.TrimSpace(string(data)); token != "" {
			return ResolvedToken{Value: token, Source: TokenSourceConfiguredFile, Path: path}, nil
		}
		return ResolvedToken{}, fmt.Errorf("configured token file %q is empty", path)
	}
	path := savedTokenPath(boot)
	data, err := os.ReadFile(path)
	if err == nil {
		if token := strings.TrimSpace(string(data)); token != "" {
			return ResolvedToken{Value: token, Source: TokenSourceSaved, Path: path}, nil
		}
	} else if !os.IsNotExist(err) {
		return ResolvedToken{}, fmt.Errorf("read saved token file %q: %w", path, err)
	}
	return ResolvedToken{}, nil
}

// EnsureToken resolves the shared secret or, when nothing is configured,
// generates a strong token, saves it to the default location, and marks the
// result Generated so the caller prints it exactly once.
func EnsureToken(boot BootConfig, explicit string) (ResolvedToken, error) {
	resolved, err := ResolveToken(boot, explicit)
	if err != nil {
		return ResolvedToken{}, err
	}
	if resolved.Value != "" {
		return resolved, nil
	}
	return GenerateAndSaveToken(boot)
}

// GenerateAndSaveToken creates a fresh 256-bit token, persists it at the
// default location, and returns it. Any previously saved token stops
// working; callers must surface the new value exactly once.
func GenerateAndSaveToken(boot BootConfig) (ResolvedToken, error) {
	buffer := make([]byte, 32)
	if _, err := rand.Read(buffer); err != nil {
		return ResolvedToken{}, fmt.Errorf("generate executor token: %w", err)
	}
	token := hex.EncodeToString(buffer)
	path := savedTokenPath(boot)
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return ResolvedToken{}, fmt.Errorf("create token directory: %w", err)
	}
	if err := atomicWrite(path, []byte(token)); err != nil {
		return ResolvedToken{}, fmt.Errorf("save executor token: %w", err)
	}
	return ResolvedToken{Value: token, Source: TokenSourceSaved, Path: path, Generated: true}, nil
}
