/**
 * Task 27 live entry — the Embed editor modal over REAL app components
 * (EmbedEditor, embed-editor/*, ui, Modal, i18n) with a demo document:
 * two embeds (weather card + report with author/footer/timestamp/fields),
 * two template variables, message content, and attachment chips. The modal
 * opens immediately so a screenshot shows the full editor + Discord preview.
 */
import { createRoot } from "react-dom/client";
import { useState } from "react";
import "../src/i18n";
import { EmbedEditor } from "../src/components/EmbedEditor";

const DEMO_DOC = {
  version: 1,
  pins: [
    { name: "city", type: "text", sample: "Berlin", default: "" },
    { name: "temp", type: "number", sample: "21", default: "" },
  ],
  embeds: [
    {
      id: "embed_1",
      title: "Weather in {{city}}",
      description: "Current conditions and the 3-day outlook, updated hourly.",
      url: "https://example.com/weather",
      color: "#00b8cc",
      timestamp: "2026-08-29T12:00:00.000Z",
      author: { name: "Neuropipe Bot", url: "", iconUrl: "" },
      footer: { text: "Powered by the Draw Image node", iconUrl: "" },
      image: { url: "" },
      thumbnail: { url: "" },
      fields: [
        { id: "f1", name: "Temperature", value: "{{temp}} °C", inline: true },
        { id: "f2", name: "Wind", value: "12 km/h", inline: true },
        { id: "f3", name: "Humidity", value: "64 %", inline: true },
        { id: "f4", name: "Outlook", value: "Cloudy skies clearing by evening with a low chance of rain.", inline: false },
      ],
    },
    {
      id: "embed_2",
      title: "Weekly report",
      description: "Attached below — generated by the pipeline.",
      url: "",
      color: "#5865F2",
      timestamp: "",
      author: { name: "", url: "", iconUrl: "" },
      footer: { text: "Sent with file attachments", iconUrl: "" },
      image: { url: "" },
      thumbnail: { url: "" },
      fields: [],
    },
  ],
};

function Harness() {
  const [value, setValue] = useState<unknown>(DEMO_DOC);
  return (
    <div className="min-h-screen bg-ink-1000 p-4" data-testid="embed-harness">
      <div className="mx-auto max-w-[420px]">
        <EmbedEditor
          value={value}
          onChange={setValue}
          previewContent="Weather report for {{city}} — details in the embeds below."
          previewAttachments={[{ name: "report.pdf" }, { name: "weather.png" }]}
        />
      </div>
      <pre className="mt-4 max-h-40 overflow-auto rounded border border-ink-700 bg-ink-950 p-2 font-mono text-[10px] text-fg-faint">
        {JSON.stringify(value, null, 2)}
      </pre>
    </div>
  );
}

createRoot(document.getElementById("root")!).render(<Harness />);
