// Neuropipe Remote Executor wire contract (v1).
//
// The executor binary is the gRPC server; the desktop application dials it.
// Complex graph payloads (FlowDefinition, Packet, CustomFunction) travel as
// versioned JSON inside bytes fields: the domain types are the single source
// of truth and already round-trip through JSON in persistence and Wails, so a
// proto mirror would only add drift risk. Identity, control-plane, and status
// fields are first-class proto fields.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.26.0
// source: executor/v1/executor.proto

package executorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Executor_GetStatus_FullMethodName        = "/neuropipe.executor.v1.Executor/GetStatus"
	Executor_GetConfig_FullMethodName        = "/neuropipe.executor.v1.Executor/GetConfig"
	Executor_UpdateConfig_FullMethodName     = "/neuropipe.executor.v1.Executor/UpdateConfig"
	Executor_DeployPipeline_FullMethodName   = "/neuropipe.executor.v1.Executor/DeployPipeline"
	Executor_UndeployPipeline_FullMethodName = "/neuropipe.executor.v1.Executor/UndeployPipeline"
	Executor_ListDeployed_FullMethodName     = "/neuropipe.executor.v1.Executor/ListDeployed"
	Executor_StartRun_FullMethodName         = "/neuropipe.executor.v1.Executor/StartRun"
	Executor_CancelRun_FullMethodName        = "/neuropipe.executor.v1.Executor/CancelRun"
	Executor_GetRun_FullMethodName           = "/neuropipe.executor.v1.Executor/GetRun"
	Executor_ListRuns_FullMethodName         = "/neuropipe.executor.v1.Executor/ListRuns"
	Executor_StreamEvents_FullMethodName     = "/neuropipe.executor.v1.Executor/StreamEvents"
	Executor_Tunnel_FullMethodName           = "/neuropipe.executor.v1.Executor/Tunnel"
)

// ExecutorClient is the client API for Executor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Executor is implemented by every remote executor installation. All methods
// require an "authorization: Bearer <token>" metadata entry whose token is
// compared constant-time against the configured shared secret.
type ExecutorClient interface {
	// GetStatus reports identity, platform, and load for health pings and the
	// Settings status display.
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*ExecutorStatus, error)
	// GetConfig returns runtime configuration. Secret material is never
	// included; write-only fields surface as *KeySet booleans instead.
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*ExecutorConfig, error)
	// UpdateConfig applies mutable runtime settings without a restart where
	// possible. Provider API keys are accepted once here and stored in the
	// executor's local vault; they cannot be read back.
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*ExecutorConfig, error)
	// DeployPipeline upserts one published pipeline bundle. Re-deploying the
	// same pipeline with a new revision replaces it atomically.
	DeployPipeline(ctx context.Context, in *DeployPipelineRequest, opts ...grpc.CallOption) (*DeployPipelineResponse, error)
	// UndeployPipeline removes a deployed bundle and stops its autonomous triggers.
	UndeployPipeline(ctx context.Context, in *UndeployPipelineRequest, opts ...grpc.CallOption) (*UndeployPipelineResponse, error)
	// ListDeployed reports deployed bundle identities for reconciliation.
	ListDeployed(ctx context.Context, in *ListDeployedRequest, opts ...grpc.CallOption) (*ListDeployedResponse, error)
	// StartRun begins an asynchronous run. Desktop-dispatched triggers and
	// editor draft runs use this entry point; embedded definitions are executed
	// ephemerally and never persisted as deployments.
	StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunResponse, error)
	// CancelRun cancels a running or queued execution.
	CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*CancelRunResponse, error)
	// GetRun returns the current snapshot of one execution.
	GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*RunSnapshot, error)
	// ListRuns returns recent executions, newest first, for reconnect
	// reconciliation of runs that finished while the desktop was disconnected.
	ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
	// StreamEvents pushes lifecycle events for executions started through this
	// connection's session. The stream ends when the client cancels it.
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecutionEvent], error)
	// Tunnel is opened by the desktop immediately after connecting and stays
	// open for the session. The executor writes HostCall frames onto its side
	// whenever a node needs a desktop-hosted service (LLM proxy, report and
	// chat write-back, SQL, Twitch send); the desktop answers with HostResponse
	// frames carrying the same request ID.
	Tunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelFrame, TunnelFrame], error)
}

type executorClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutorClient(cc grpc.ClientConnInterface) ExecutorClient {
	return &executorClient{cc}
}

func (c *executorClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*ExecutorStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutorStatus)
	err := c.cc.Invoke(ctx, Executor_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*ExecutorConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutorConfig)
	err := c.cc.Invoke(ctx, Executor_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*ExecutorConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutorConfig)
	err := c.cc.Invoke(ctx, Executor_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) DeployPipeline(ctx context.Context, in *DeployPipelineRequest, opts ...grpc.CallOption) (*DeployPipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeployPipelineResponse)
	err := c.cc.Invoke(ctx, Executor_DeployPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) UndeployPipeline(ctx context.Context, in *UndeployPipelineRequest, opts ...grpc.CallOption) (*UndeployPipelineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndeployPipelineResponse)
	err := c.cc.Invoke(ctx, Executor_UndeployPipeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) ListDeployed(ctx context.Context, in *ListDeployedRequest, opts ...grpc.CallOption) (*ListDeployedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeployedResponse)
	err := c.cc.Invoke(ctx, Executor_ListDeployed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRunResponse)
	err := c.cc.Invoke(ctx, Executor_StartRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*CancelRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelRunResponse)
	err := c.cc.Invoke(ctx, Executor_CancelRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*RunSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunSnapshot)
	err := c.cc.Invoke(ctx, Executor_GetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, Executor_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecutionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Executor_ServiceDesc.Streams[0], Executor_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, ExecutionEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Executor_StreamEventsClient = grpc.ServerStreamingClient[ExecutionEvent]

func (c *executorClient) Tunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelFrame, TunnelFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Executor_ServiceDesc.Streams[1], Executor_Tunnel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TunnelFrame, TunnelFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Executor_TunnelClient = grpc.BidiStreamingClient[TunnelFrame, TunnelFrame]

// ExecutorServer is the server API for Executor service.
// All implementations must embed UnimplementedExecutorServer
// for forward compatibility.
//
// Executor is implemented by every remote executor installation. All methods
// require an "authorization: Bearer <token>" metadata entry whose token is
// compared constant-time against the configured shared secret.
type ExecutorServer interface {
	// GetStatus reports identity, platform, and load for health pings and the
	// Settings status display.
	GetStatus(context.Context, *StatusRequest) (*ExecutorStatus, error)
	// GetConfig returns runtime configuration. Secret material is never
	// included; write-only fields surface as *KeySet booleans instead.
	GetConfig(context.Context, *GetConfigRequest) (*ExecutorConfig, error)
	// UpdateConfig applies mutable runtime settings without a restart where
	// possible. Provider API keys are accepted once here and stored in the
	// executor's local vault; they cannot be read back.
	UpdateConfig(context.Context, *UpdateConfigRequest) (*ExecutorConfig, error)
	// DeployPipeline upserts one published pipeline bundle. Re-deploying the
	// same pipeline with a new revision replaces it atomically.
	DeployPipeline(context.Context, *DeployPipelineRequest) (*DeployPipelineResponse, error)
	// UndeployPipeline removes a deployed bundle and stops its autonomous triggers.
	UndeployPipeline(context.Context, *UndeployPipelineRequest) (*UndeployPipelineResponse, error)
	// ListDeployed reports deployed bundle identities for reconciliation.
	ListDeployed(context.Context, *ListDeployedRequest) (*ListDeployedResponse, error)
	// StartRun begins an asynchronous run. Desktop-dispatched triggers and
	// editor draft runs use this entry point; embedded definitions are executed
	// ephemerally and never persisted as deployments.
	StartRun(context.Context, *StartRunRequest) (*StartRunResponse, error)
	// CancelRun cancels a running or queued execution.
	CancelRun(context.Context, *CancelRunRequest) (*CancelRunResponse, error)
	// GetRun returns the current snapshot of one execution.
	GetRun(context.Context, *GetRunRequest) (*RunSnapshot, error)
	// ListRuns returns recent executions, newest first, for reconnect
	// reconciliation of runs that finished while the desktop was disconnected.
	ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error)
	// StreamEvents pushes lifecycle events for executions started through this
	// connection's session. The stream ends when the client cancels it.
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[ExecutionEvent]) error
	// Tunnel is opened by the desktop immediately after connecting and stays
	// open for the session. The executor writes HostCall frames onto its side
	// whenever a node needs a desktop-hosted service (LLM proxy, report and
	// chat write-back, SQL, Twitch send); the desktop answers with HostResponse
	// frames carrying the same request ID.
	Tunnel(grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]) error
	mustEmbedUnimplementedExecutorServer()
}

// UnimplementedExecutorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutorServer struct{}

func (UnimplementedExecutorServer) GetStatus(context.Context, *StatusRequest) (*ExecutorStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedExecutorServer) GetConfig(context.Context, *GetConfigRequest) (*ExecutorConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedExecutorServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*ExecutorConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedExecutorServer) DeployPipeline(context.Context, *DeployPipelineRequest) (*DeployPipelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeployPipeline not implemented")
}
func (UnimplementedExecutorServer) UndeployPipeline(context.Context, *UndeployPipelineRequest) (*UndeployPipelineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UndeployPipeline not implemented")
}
func (UnimplementedExecutorServer) ListDeployed(context.Context, *ListDeployedRequest) (*ListDeployedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDeployed not implemented")
}
func (UnimplementedExecutorServer) StartRun(context.Context, *StartRunRequest) (*StartRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRun not implemented")
}
func (UnimplementedExecutorServer) CancelRun(context.Context, *CancelRunRequest) (*CancelRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRun not implemented")
}
func (UnimplementedExecutorServer) GetRun(context.Context, *GetRunRequest) (*RunSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedExecutorServer) ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedExecutorServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[ExecutionEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedExecutorServer) Tunnel(grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]) error {
	return status.Error(codes.Unimplemented, "method Tunnel not implemented")
}
func (UnimplementedExecutorServer) mustEmbedUnimplementedExecutorServer() {}
func (UnimplementedExecutorServer) testEmbeddedByValue()                  {}

// UnsafeExecutorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutorServer will
// result in compilation errors.
type UnsafeExecutorServer interface {
	mustEmbedUnimplementedExecutorServer()
}

func RegisterExecutorServer(s grpc.ServiceRegistrar, srv ExecutorServer) {
	// If the following call panics, it indicates UnimplementedExecutorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Executor_ServiceDesc, srv)
}

func _Executor_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Executor_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Executor_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Executor_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_DeployPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployPipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).DeployPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Executor_DeployPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).DeployPipeline(ctx, req.(*DeployPipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_UndeployPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndeployPipelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).UndeployPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Executor_UndeployPipeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).UndeployPipeline(ctx, req.(*UndeployPipelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_ListDeployed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeployedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).ListDeployed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Executor_ListDeployed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).ListDeployed(ctx, req.(*ListDeployedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_StartRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).StartRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Executor_StartRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).StartRun(ctx, req.(*StartRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_CancelRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).CancelRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Executor_CancelRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).CancelRun(ctx, req.(*CancelRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Executor_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).GetRun(ctx, req.(*GetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Executor_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServer).ListRuns(ctx, req.(*ListRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Executor_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ExecutorServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, ExecutionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Executor_StreamEventsServer = grpc.ServerStreamingServer[ExecutionEvent]

func _Executor_Tunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExecutorServer).Tunnel(&grpc.GenericServerStream[TunnelFrame, TunnelFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Executor_TunnelServer = grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]

// Executor_ServiceDesc is the grpc.ServiceDesc for Executor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Executor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "neuropipe.executor.v1.Executor",
	HandlerType: (*ExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _Executor_GetStatus_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _Executor_GetConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _Executor_UpdateConfig_Handler,
		},
		{
			MethodName: "DeployPipeline",
			Handler:    _Executor_DeployPipeline_Handler,
		},
		{
			MethodName: "UndeployPipeline",
			Handler:    _Executor_UndeployPipeline_Handler,
		},
		{
			MethodName: "ListDeployed",
			Handler:    _Executor_ListDeployed_Handler,
		},
		{
			MethodName: "StartRun",
			Handler:    _Executor_StartRun_Handler,
		},
		{
			MethodName: "CancelRun",
			Handler:    _Executor_CancelRun_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _Executor_GetRun_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _Executor_ListRuns_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _Executor_StreamEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Tunnel",
			Handler:       _Executor_Tunnel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "executor/v1/executor.proto",
}
