// Neuropipe Remote Executor wire contract (v1).
//
// The executor binary is the gRPC server; the desktop application dials it.
// Complex graph payloads (FlowDefinition, Packet, CustomFunction) travel as
// versioned JSON inside bytes fields: the domain types are the single source
// of truth and already round-trip through JSON in persistence and Wails, so a
// proto mirror would only add drift risk. Identity, control-plane, and status
// fields are first-class proto fields.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.0
// source: executor/v1/executor.proto

package executorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_executor_v1_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{0}
}

type ExecutorStatus struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ExecutorVersion        string                 `protobuf:"bytes,1,opt,name=executor_version,json=executorVersion,proto3" json:"executor_version,omitempty"`
	Platform               string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"` // GOOS/GOARCH of the running executor
	BlueprintSchemaVersion int32                  `protobuf:"varint,3,opt,name=blueprint_schema_version,json=blueprintSchemaVersion,proto3" json:"blueprint_schema_version,omitempty"`
	UptimeSeconds          int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ActiveRuns             int32                  `protobuf:"varint,5,opt,name=active_runs,json=activeRuns,proto3" json:"active_runs,omitempty"`
	MaxConcurrentRuns      int32                  `protobuf:"varint,6,opt,name=max_concurrent_runs,json=maxConcurrentRuns,proto3" json:"max_concurrent_runs,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ExecutorStatus) Reset() {
	*x = ExecutorStatus{}
	mi := &file_executor_v1_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorStatus) ProtoMessage() {}

func (x *ExecutorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorStatus.ProtoReflect.Descriptor instead.
func (*ExecutorStatus) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutorStatus) GetExecutorVersion() string {
	if x != nil {
		return x.ExecutorVersion
	}
	return ""
}

func (x *ExecutorStatus) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ExecutorStatus) GetBlueprintSchemaVersion() int32 {
	if x != nil {
		return x.BlueprintSchemaVersion
	}
	return 0
}

func (x *ExecutorStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ExecutorStatus) GetActiveRuns() int32 {
	if x != nil {
		return x.ActiveRuns
	}
	return 0
}

func (x *ExecutorStatus) GetMaxConcurrentRuns() int32 {
	if x != nil {
		return x.MaxConcurrentRuns
	}
	return 0
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_executor_v1_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{2}
}

type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ExecutorConfig        `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_executor_v1_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateConfigRequest) GetConfig() *ExecutorConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// ExecutorConfig is the RPC-managed subset of executor settings. Static boot
// settings (listen address, TLS, data dir, auth token) live in the executor's
// config file and are intentionally not writable over the network.
type ExecutorConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "proxy" forwards LLM calls to the desktop over Tunnel; "local" uses the
	// providers below with credentials from the executor's own vault.
	LlmMode           string              `protobuf:"bytes,1,opt,name=llm_mode,json=llmMode,proto3" json:"llm_mode,omitempty"`
	Providers         []*ExecutorProvider `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
	DefaultProviderId string              `protobuf:"bytes,3,opt,name=default_provider_id,json=defaultProviderId,proto3" json:"default_provider_id,omitempty"`
	MaxConcurrentRuns int32               `protobuf:"varint,4,opt,name=max_concurrent_runs,json=maxConcurrentRuns,proto3" json:"max_concurrent_runs,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExecutorConfig) Reset() {
	*x = ExecutorConfig{}
	mi := &file_executor_v1_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorConfig) ProtoMessage() {}

func (x *ExecutorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorConfig.ProtoReflect.Descriptor instead.
func (*ExecutorConfig) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutorConfig) GetLlmMode() string {
	if x != nil {
		return x.LlmMode
	}
	return ""
}

func (x *ExecutorConfig) GetProviders() []*ExecutorProvider {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *ExecutorConfig) GetDefaultProviderId() string {
	if x != nil {
		return x.DefaultProviderId
	}
	return ""
}

func (x *ExecutorConfig) GetMaxConcurrentRuns() int32 {
	if x != nil {
		return x.MaxConcurrentRuns
	}
	return 0
}

type ExecutorProvider struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind    string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // mirrors domain.ProviderKind
	BaseUrl string                 `protobuf:"bytes,4,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Model   string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Enabled bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Write-only on UpdateConfig; GetConfig only reports api_key_set.
	ApiKey        string `protobuf:"bytes,7,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiKeySet     bool   `protobuf:"varint,8,opt,name=api_key_set,json=apiKeySet,proto3" json:"api_key_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutorProvider) Reset() {
	*x = ExecutorProvider{}
	mi := &file_executor_v1_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutorProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorProvider) ProtoMessage() {}

func (x *ExecutorProvider) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorProvider.ProtoReflect.Descriptor instead.
func (*ExecutorProvider) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{5}
}

func (x *ExecutorProvider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecutorProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecutorProvider) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ExecutorProvider) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ExecutorProvider) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ExecutorProvider) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ExecutorProvider) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ExecutorProvider) GetApiKeySet() bool {
	if x != nil {
		return x.ApiKeySet
	}
	return false
}

type DeployPipelineRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	PipelineId             string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description            string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Icon                   string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	IconColor              string                 `protobuf:"bytes,5,opt,name=icon_color,json=iconColor,proto3" json:"icon_color,omitempty"`
	IconBackground         string                 `protobuf:"bytes,6,opt,name=icon_background,json=iconBackground,proto3" json:"icon_background,omitempty"`
	Revision               int64                  `protobuf:"varint,7,opt,name=revision,proto3" json:"revision,omitempty"`
	BlueprintSchemaVersion int32                  `protobuf:"varint,8,opt,name=blueprint_schema_version,json=blueprintSchemaVersion,proto3" json:"blueprint_schema_version,omitempty"`
	// JSON-encoded domain.FlowDefinition.
	DefinitionJson []byte `protobuf:"bytes,9,opt,name=definition_json,json=definitionJson,proto3" json:"definition_json,omitempty"`
	// JSON-encoded published domain.CustomFunction values required by the
	// definition, resolved recursively by the desktop before deploy.
	FunctionsJson [][]byte `protobuf:"bytes,10,rep,name=functions_json,json=functionsJson,proto3" json:"functions_json,omitempty"`
	// Autonomous trigger bindings carried with the deployment.
	Triggers []*DeployedTrigger `protobuf:"bytes,11,rep,name=triggers,proto3" json:"triggers,omitempty"`
	// Capability allowlist granted to this revision at publish time.
	Capabilities  []string `protobuf:"bytes,12,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployPipelineRequest) Reset() {
	*x = DeployPipelineRequest{}
	mi := &file_executor_v1_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployPipelineRequest) ProtoMessage() {}

func (x *DeployPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployPipelineRequest.ProtoReflect.Descriptor instead.
func (*DeployPipelineRequest) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{6}
}

func (x *DeployPipelineRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *DeployPipelineRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployPipelineRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DeployPipelineRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *DeployPipelineRequest) GetIconColor() string {
	if x != nil {
		return x.IconColor
	}
	return ""
}

func (x *DeployPipelineRequest) GetIconBackground() string {
	if x != nil {
		return x.IconBackground
	}
	return ""
}

func (x *DeployPipelineRequest) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DeployPipelineRequest) GetBlueprintSchemaVersion() int32 {
	if x != nil {
		return x.BlueprintSchemaVersion
	}
	return 0
}

func (x *DeployPipelineRequest) GetDefinitionJson() []byte {
	if x != nil {
		return x.DefinitionJson
	}
	return nil
}

func (x *DeployPipelineRequest) GetFunctionsJson() [][]byte {
	if x != nil {
		return x.FunctionsJson
	}
	return nil
}

func (x *DeployPipelineRequest) GetTriggers() []*DeployedTrigger {
	if x != nil {
		return x.Triggers
	}
	return nil
}

func (x *DeployPipelineRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type DeployPipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployPipelineResponse) Reset() {
	*x = DeployPipelineResponse{}
	mi := &file_executor_v1_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployPipelineResponse) ProtoMessage() {}

func (x *DeployPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployPipelineResponse.ProtoReflect.Descriptor instead.
func (*DeployPipelineResponse) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{7}
}

type DeployedTrigger struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BindingId      string                 `protobuf:"bytes,1,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"` // desktop trigger-binding identity for last-run sync
	NodeId         string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeType       string                 `protobuf:"bytes,3,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"` // e.g. "trigger:cron", "trigger:file_watch"
	Kind           string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`                         // mirrors domain.TriggerKind
	Label          string                 `protobuf:"bytes,5,opt,name=label,proto3" json:"label,omitempty"`
	Enabled        bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Trusted        bool                   `protobuf:"varint,7,opt,name=trusted,proto3" json:"trusted,omitempty"` // unattended approval captured at deploy time
	Cron           string                 `protobuf:"bytes,8,opt,name=cron,proto3" json:"cron,omitempty"`
	Timezone       string                 `protobuf:"bytes,9,opt,name=timezone,proto3" json:"timezone,omitempty"`
	WatchPath      string                 `protobuf:"bytes,10,opt,name=watch_path,json=watchPath,proto3" json:"watch_path,omitempty"` // file-watch path, resolved on the executor machine
	WatchRecursive bool                   `protobuf:"varint,11,opt,name=watch_recursive,json=watchRecursive,proto3" json:"watch_recursive,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeployedTrigger) Reset() {
	*x = DeployedTrigger{}
	mi := &file_executor_v1_executor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployedTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployedTrigger) ProtoMessage() {}

func (x *DeployedTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployedTrigger.ProtoReflect.Descriptor instead.
func (*DeployedTrigger) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{8}
}

func (x *DeployedTrigger) GetBindingId() string {
	if x != nil {
		return x.BindingId
	}
	return ""
}

func (x *DeployedTrigger) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DeployedTrigger) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *DeployedTrigger) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DeployedTrigger) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DeployedTrigger) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DeployedTrigger) GetTrusted() bool {
	if x != nil {
		return x.Trusted
	}
	return false
}

func (x *DeployedTrigger) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *DeployedTrigger) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *DeployedTrigger) GetWatchPath() string {
	if x != nil {
		return x.WatchPath
	}
	return ""
}

func (x *DeployedTrigger) GetWatchRecursive() bool {
	if x != nil {
		return x.WatchRecursive
	}
	return false
}

type UndeployPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeployPipelineRequest) Reset() {
	*x = UndeployPipelineRequest{}
	mi := &file_executor_v1_executor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeployPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeployPipelineRequest) ProtoMessage() {}

func (x *UndeployPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeployPipelineRequest.ProtoReflect.Descriptor instead.
func (*UndeployPipelineRequest) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{9}
}

func (x *UndeployPipelineRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

type UndeployPipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeployPipelineResponse) Reset() {
	*x = UndeployPipelineResponse{}
	mi := &file_executor_v1_executor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeployPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeployPipelineResponse) ProtoMessage() {}

func (x *UndeployPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeployPipelineResponse.ProtoReflect.Descriptor instead.
func (*UndeployPipelineResponse) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{10}
}

type ListDeployedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeployedRequest) Reset() {
	*x = ListDeployedRequest{}
	mi := &file_executor_v1_executor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeployedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeployedRequest) ProtoMessage() {}

func (x *ListDeployedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeployedRequest.ProtoReflect.Descriptor instead.
func (*ListDeployedRequest) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{11}
}

type ListDeployedResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Pipelines     []*DeployedPipelineInfo `protobuf:"bytes,1,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeployedResponse) Reset() {
	*x = ListDeployedResponse{}
	mi := &file_executor_v1_executor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeployedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeployedResponse) ProtoMessage() {}

func (x *ListDeployedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeployedResponse.ProtoReflect.Descriptor instead.
func (*ListDeployedResponse) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{12}
}

func (x *ListDeployedResponse) GetPipelines() []*DeployedPipelineInfo {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

type DeployedPipelineInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Revision      int64                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	TriggerCount  int32                  `protobuf:"varint,4,opt,name=trigger_count,json=triggerCount,proto3" json:"trigger_count,omitempty"`
	DeployedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deployed_at,json=deployedAt,proto3" json:"deployed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployedPipelineInfo) Reset() {
	*x = DeployedPipelineInfo{}
	mi := &file_executor_v1_executor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployedPipelineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployedPipelineInfo) ProtoMessage() {}

func (x *DeployedPipelineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployedPipelineInfo.ProtoReflect.Descriptor instead.
func (*DeployedPipelineInfo) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{13}
}

func (x *DeployedPipelineInfo) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *DeployedPipelineInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployedPipelineInfo) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DeployedPipelineInfo) GetTriggerCount() int32 {
	if x != nil {
		return x.TriggerCount
	}
	return 0
}

func (x *DeployedPipelineInfo) GetDeployedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeployedAt
	}
	return nil
}

type StartRunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlation ID assigned by the desktop; echoed in every event.
	ExecutionId string `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	PipelineId  string `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	// Zero selects the newest deployed revision.
	Revision         int64  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	TriggerNodeId    string `protobuf:"bytes,4,opt,name=trigger_node_id,json=triggerNodeId,proto3" json:"trigger_node_id,omitempty"`
	TriggerBindingId string `protobuf:"bytes,5,opt,name=trigger_binding_id,json=triggerBindingId,proto3" json:"trigger_binding_id,omitempty"`
	Unattended       bool   `protobuf:"varint,6,opt,name=unattended,proto3" json:"unattended,omitempty"`
	// Optional chat-run correlation forwarded to chat nodes.
	ChatRunId string `protobuf:"bytes,7,opt,name=chat_run_id,json=chatRunId,proto3" json:"chat_run_id,omitempty"`
	// JSON-encoded pipeline.Packet input.
	InputJson []byte `protobuf:"bytes,8,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	// Optional JSON-encoded domain.FlowDefinition for ephemeral draft runs.
	EmbeddedDefinitionJson []byte `protobuf:"bytes,9,opt,name=embedded_definition_json,json=embeddedDefinitionJson,proto3" json:"embedded_definition_json,omitempty"`
	BlueprintSchemaVersion int32  `protobuf:"varint,10,opt,name=blueprint_schema_version,json=blueprintSchemaVersion,proto3" json:"blueprint_schema_version,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StartRunRequest) Reset() {
	*x = StartRunRequest{}
	mi := &file_executor_v1_executor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunRequest) ProtoMessage() {}

func (x *StartRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunRequest.ProtoReflect.Descriptor instead.
func (*StartRunRequest) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{14}
}

func (x *StartRunRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *StartRunRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *StartRunRequest) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *StartRunRequest) GetTriggerNodeId() string {
	if x != nil {
		return x.TriggerNodeId
	}
	return ""
}

func (x *StartRunRequest) GetTriggerBindingId() string {
	if x != nil {
		return x.TriggerBindingId
	}
	return ""
}

func (x *StartRunRequest) GetUnattended() bool {
	if x != nil {
		return x.Unattended
	}
	return false
}

func (x *StartRunRequest) GetChatRunId() string {
	if x != nil {
		return x.ChatRunId
	}
	return ""
}

func (x *StartRunRequest) GetInputJson() []byte {
	if x != nil {
		return x.InputJson
	}
	return nil
}

func (x *StartRunRequest) GetEmbeddedDefinitionJson() []byte {
	if x != nil {
		return x.EmbeddedDefinitionJson
	}
	return nil
}

func (x *StartRunRequest) GetBlueprintSchemaVersion() int32 {
	if x != nil {
		return x.BlueprintSchemaVersion
	}
	return 0
}

type StartRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRunResponse) Reset() {
	*x = StartRunResponse{}
	mi := &file_executor_v1_executor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRunResponse) ProtoMessage() {}

func (x *StartRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRunResponse.ProtoReflect.Descriptor instead.
func (*StartRunResponse) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{15}
}

type CancelRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_executor_v1_executor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{16}
}

func (x *CancelRunRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type CancelRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunResponse) Reset() {
	*x = CancelRunResponse{}
	mi := &file_executor_v1_executor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunResponse) ProtoMessage() {}

func (x *CancelRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunResponse.ProtoReflect.Descriptor instead.
func (*CancelRunResponse) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{17}
}

type GetRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunRequest) Reset() {
	*x = GetRunRequest{}
	mi := &file_executor_v1_executor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunRequest) ProtoMessage() {}

func (x *GetRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunRequest.ProtoReflect.Descriptor instead.
func (*GetRunRequest) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{18}
}

func (x *GetRunRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type ListRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // zero means the executor default page size
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_executor_v1_executor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{19}
}

func (x *ListRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*RunSnapshot         `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_executor_v1_executor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{20}
}

func (x *ListRunsResponse) GetRuns() []*RunSnapshot {
	if x != nil {
		return x.Runs
	}
	return nil
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_executor_v1_executor_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{21}
}

type ExecutionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *RunSnapshot           `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionEvent) Reset() {
	*x = ExecutionEvent{}
	mi := &file_executor_v1_executor_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionEvent) ProtoMessage() {}

func (x *ExecutionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionEvent.ProtoReflect.Descriptor instead.
func (*ExecutionEvent) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{22}
}

func (x *ExecutionEvent) GetRun() *RunSnapshot {
	if x != nil {
		return x.Run
	}
	return nil
}

type RunSnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId      string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	PipelineId       string                 `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	TriggerNodeId    string                 `protobuf:"bytes,3,opt,name=trigger_node_id,json=triggerNodeId,proto3" json:"trigger_node_id,omitempty"`
	TriggerBindingId string                 `protobuf:"bytes,4,opt,name=trigger_binding_id,json=triggerBindingId,proto3" json:"trigger_binding_id,omitempty"`
	Revision         int64                  `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // mirrors domain.RunStatus
	Error            string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"` // record creation time
	FinishedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	NodeRuns         []*NodeRun             `protobuf:"bytes,10,rep,name=node_runs,json=nodeRuns,proto3" json:"node_runs,omitempty"`
	ChatRunId        string                 `protobuf:"bytes,11,opt,name=chat_run_id,json=chatRunId,proto3" json:"chat_run_id,omitempty"`
	RunStartedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=run_started_at,json=runStartedAt,proto3" json:"run_started_at,omitempty"` // actual execution start
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunSnapshot) Reset() {
	*x = RunSnapshot{}
	mi := &file_executor_v1_executor_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSnapshot) ProtoMessage() {}

func (x *RunSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSnapshot.ProtoReflect.Descriptor instead.
func (*RunSnapshot) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{23}
}

func (x *RunSnapshot) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *RunSnapshot) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *RunSnapshot) GetTriggerNodeId() string {
	if x != nil {
		return x.TriggerNodeId
	}
	return ""
}

func (x *RunSnapshot) GetTriggerBindingId() string {
	if x != nil {
		return x.TriggerBindingId
	}
	return ""
}

func (x *RunSnapshot) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *RunSnapshot) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunSnapshot) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RunSnapshot) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *RunSnapshot) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *RunSnapshot) GetNodeRuns() []*NodeRun {
	if x != nil {
		return x.NodeRuns
	}
	return nil
}

func (x *RunSnapshot) GetChatRunId() string {
	if x != nil {
		return x.ChatRunId
	}
	return ""
}

func (x *RunSnapshot) GetRunStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RunStartedAt
	}
	return nil
}

type NodeRun struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeType         string                 `protobuf:"bytes,2,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	ParentNodeId     string                 `protobuf:"bytes,3,opt,name=parent_node_id,json=parentNodeId,proto3" json:"parent_node_id,omitempty"`
	FunctionId       string                 `protobuf:"bytes,4,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	FunctionRevision int32                  `protobuf:"varint,5,opt,name=function_revision,json=functionRevision,proto3" json:"function_revision,omitempty"`
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Error            string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeRun) Reset() {
	*x = NodeRun{}
	mi := &file_executor_v1_executor_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRun) ProtoMessage() {}

func (x *NodeRun) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRun.ProtoReflect.Descriptor instead.
func (*NodeRun) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{24}
}

func (x *NodeRun) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeRun) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *NodeRun) GetParentNodeId() string {
	if x != nil {
		return x.ParentNodeId
	}
	return ""
}

func (x *NodeRun) GetFunctionId() string {
	if x != nil {
		return x.FunctionId
	}
	return ""
}

func (x *NodeRun) GetFunctionRevision() int32 {
	if x != nil {
		return x.FunctionRevision
	}
	return 0
}

func (x *NodeRun) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeRun) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *NodeRun) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *NodeRun) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type TunnelFrame struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TunnelFrame_Call
	//	*TunnelFrame_Response
	Payload       isTunnelFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelFrame) Reset() {
	*x = TunnelFrame{}
	mi := &file_executor_v1_executor_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelFrame) ProtoMessage() {}

func (x *TunnelFrame) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelFrame.ProtoReflect.Descriptor instead.
func (*TunnelFrame) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{25}
}

func (x *TunnelFrame) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TunnelFrame) GetPayload() isTunnelFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TunnelFrame) GetCall() *HostCall {
	if x != nil {
		if x, ok := x.Payload.(*TunnelFrame_Call); ok {
			return x.Call
		}
	}
	return nil
}

func (x *TunnelFrame) GetResponse() *HostResponse {
	if x != nil {
		if x, ok := x.Payload.(*TunnelFrame_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isTunnelFrame_Payload interface {
	isTunnelFrame_Payload()
}

type TunnelFrame_Call struct {
	Call *HostCall `protobuf:"bytes,2,opt,name=call,proto3,oneof"`
}

type TunnelFrame_Response struct {
	Response *HostResponse `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

func (*TunnelFrame_Call) isTunnelFrame_Payload() {}

func (*TunnelFrame_Response) isTunnelFrame_Payload() {}

type HostCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"` // llm.chat | llm.converse | report.create | chat.append_reply |
	// chat.update_status | chat.read_history | sql.query | twitch.send_message
	PayloadJson   []byte `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostCall) Reset() {
	*x = HostCall{}
	mi := &file_executor_v1_executor_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCall) ProtoMessage() {}

func (x *HostCall) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCall.ProtoReflect.Descriptor instead.
func (*HostCall) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{26}
}

func (x *HostCall) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *HostCall) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

type HostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostResponse) Reset() {
	*x = HostResponse{}
	mi := &file_executor_v1_executor_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostResponse) ProtoMessage() {}

func (x *HostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_v1_executor_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostResponse.ProtoReflect.Descriptor instead.
func (*HostResponse) Descriptor() ([]byte, []int) {
	return file_executor_v1_executor_proto_rawDescGZIP(), []int{27}
}

func (x *HostResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HostResponse) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

func (x *HostResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_executor_v1_executor_proto protoreflect.FileDescriptor

const file_executor_v1_executor_proto_rawDesc = "" +
	"\n" +
	"\x1aexecutor/v1/executor.proto\x12\x15neuropipe.executor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0f\n" +
	"\rStatusRequest\"\x89\x02\n" +
	"\x0eExecutorStatus\x12)\n" +
	"\x10executor_version\x18\x01 \x01(\tR\x0fexecutorVersion\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x128\n" +
	"\x18blueprint_schema_version\x18\x03 \x01(\x05R\x16blueprintSchemaVersion\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12\x1f\n" +
	"\vactive_runs\x18\x05 \x01(\x05R\n" +
	"activeRuns\x12.\n" +
	"\x13max_concurrent_runs\x18\x06 \x01(\x05R\x11maxConcurrentRuns\"\x12\n" +
	"\x10GetConfigRequest\"T\n" +
	"\x13UpdateConfigRequest\x12=\n" +
	"\x06config\x18\x01 \x01(\v2%.neuropipe.executor.v1.ExecutorConfigR\x06config\"\xd2\x01\n" +
	"\x0eExecutorConfig\x12\x19\n" +
	"\bllm_mode\x18\x01 \x01(\tR\allmMode\x12E\n" +
	"\tproviders\x18\x02 \x03(\v2'.neuropipe.executor.v1.ExecutorProviderR\tproviders\x12.\n" +
	"\x13default_provider_id\x18\x03 \x01(\tR\x11defaultProviderId\x12.\n" +
	"\x13max_concurrent_runs\x18\x04 \x01(\x05R\x11maxConcurrentRuns\"\xce\x01\n" +
	"\x10ExecutorProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x19\n" +
	"\bbase_url\x18\x04 \x01(\tR\abaseUrl\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12\x17\n" +
	"\aapi_key\x18\a \x01(\tR\x06apiKey\x12\x1e\n" +
	"\vapi_key_set\x18\b \x01(\bR\tapiKeySet\"\xd8\x03\n" +
	"\x15DeployPipelineRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x1d\n" +
	"\n" +
	"icon_color\x18\x05 \x01(\tR\ticonColor\x12'\n" +
	"\x0ficon_background\x18\x06 \x01(\tR\x0eiconBackground\x12\x1a\n" +
	"\brevision\x18\a \x01(\x03R\brevision\x128\n" +
	"\x18blueprint_schema_version\x18\b \x01(\x05R\x16blueprintSchemaVersion\x12'\n" +
	"\x0fdefinition_json\x18\t \x01(\fR\x0edefinitionJson\x12%\n" +
	"\x0efunctions_json\x18\n" +
	" \x03(\fR\rfunctionsJson\x12B\n" +
	"\btriggers\x18\v \x03(\v2&.neuropipe.executor.v1.DeployedTriggerR\btriggers\x12\"\n" +
	"\fcapabilities\x18\f \x03(\tR\fcapabilities\"\x18\n" +
	"\x16DeployPipelineResponse\"\xbc\x02\n" +
	"\x0fDeployedTrigger\x12\x1d\n" +
	"\n" +
	"binding_id\x18\x01 \x01(\tR\tbindingId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_type\x18\x03 \x01(\tR\bnodeType\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x14\n" +
	"\x05label\x18\x05 \x01(\tR\x05label\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12\x18\n" +
	"\atrusted\x18\a \x01(\bR\atrusted\x12\x12\n" +
	"\x04cron\x18\b \x01(\tR\x04cron\x12\x1a\n" +
	"\btimezone\x18\t \x01(\tR\btimezone\x12\x1d\n" +
	"\n" +
	"watch_path\x18\n" +
	" \x01(\tR\twatchPath\x12'\n" +
	"\x0fwatch_recursive\x18\v \x01(\bR\x0ewatchRecursive\":\n" +
	"\x17UndeployPipelineRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\"\x1a\n" +
	"\x18UndeployPipelineResponse\"\x15\n" +
	"\x13ListDeployedRequest\"a\n" +
	"\x14ListDeployedResponse\x12I\n" +
	"\tpipelines\x18\x01 \x03(\v2+.neuropipe.executor.v1.DeployedPipelineInfoR\tpipelines\"\xc9\x01\n" +
	"\x14DeployedPipelineInfo\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\x12#\n" +
	"\rtrigger_count\x18\x04 \x01(\x05R\ftriggerCount\x12;\n" +
	"\vdeployed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"deployedAt\"\x9a\x03\n" +
	"\x0fStartRunRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\x12&\n" +
	"\x0ftrigger_node_id\x18\x04 \x01(\tR\rtriggerNodeId\x12,\n" +
	"\x12trigger_binding_id\x18\x05 \x01(\tR\x10triggerBindingId\x12\x1e\n" +
	"\n" +
	"unattended\x18\x06 \x01(\bR\n" +
	"unattended\x12\x1e\n" +
	"\vchat_run_id\x18\a \x01(\tR\tchatRunId\x12\x1d\n" +
	"\n" +
	"input_json\x18\b \x01(\fR\tinputJson\x128\n" +
	"\x18embedded_definition_json\x18\t \x01(\fR\x16embeddedDefinitionJson\x128\n" +
	"\x18blueprint_schema_version\x18\n" +
	" \x01(\x05R\x16blueprintSchemaVersion\"\x12\n" +
	"\x10StartRunResponse\"5\n" +
	"\x10CancelRunRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\x13\n" +
	"\x11CancelRunResponse\"2\n" +
	"\rGetRunRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"'\n" +
	"\x0fListRunsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"J\n" +
	"\x10ListRunsResponse\x126\n" +
	"\x04runs\x18\x01 \x03(\v2\".neuropipe.executor.v1.RunSnapshotR\x04runs\"\x15\n" +
	"\x13StreamEventsRequest\"F\n" +
	"\x0eExecutionEvent\x124\n" +
	"\x03run\x18\x01 \x01(\v2\".neuropipe.executor.v1.RunSnapshotR\x03run\"\x88\x04\n" +
	"\vRunSnapshot\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1f\n" +
	"\vpipeline_id\x18\x02 \x01(\tR\n" +
	"pipelineId\x12&\n" +
	"\x0ftrigger_node_id\x18\x03 \x01(\tR\rtriggerNodeId\x12,\n" +
	"\x12trigger_binding_id\x18\x04 \x01(\tR\x10triggerBindingId\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\x03R\brevision\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12;\n" +
	"\tnode_runs\x18\n" +
	" \x03(\v2\x1e.neuropipe.executor.v1.NodeRunR\bnodeRuns\x12\x1e\n" +
	"\vchat_run_id\x18\v \x01(\tR\tchatRunId\x12@\n" +
	"\x0erun_started_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\frunStartedAt\"\xd9\x02\n" +
	"\aNodeRun\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_type\x18\x02 \x01(\tR\bnodeType\x12$\n" +
	"\x0eparent_node_id\x18\x03 \x01(\tR\fparentNodeId\x12\x1f\n" +
	"\vfunction_id\x18\x04 \x01(\tR\n" +
	"functionId\x12+\n" +
	"\x11function_revision\x18\x05 \x01(\x05R\x10functionRevision\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"\xb1\x01\n" +
	"\vTunnelFrame\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x125\n" +
	"\x04call\x18\x02 \x01(\v2\x1f.neuropipe.executor.v1.HostCallH\x00R\x04call\x12A\n" +
	"\bresponse\x18\x03 \x01(\v2#.neuropipe.executor.v1.HostResponseH\x00R\bresponseB\t\n" +
	"\apayload\"A\n" +
	"\bHostCall\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\fR\vpayloadJson\"W\n" +
	"\fHostResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\fR\vpayloadJson\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\x9a\t\n" +
	"\bExecutor\x12X\n" +
	"\tGetStatus\x12$.neuropipe.executor.v1.StatusRequest\x1a%.neuropipe.executor.v1.ExecutorStatus\x12[\n" +
	"\tGetConfig\x12'.neuropipe.executor.v1.GetConfigRequest\x1a%.neuropipe.executor.v1.ExecutorConfig\x12a\n" +
	"\fUpdateConfig\x12*.neuropipe.executor.v1.UpdateConfigRequest\x1a%.neuropipe.executor.v1.ExecutorConfig\x12m\n" +
	"\x0eDeployPipeline\x12,.neuropipe.executor.v1.DeployPipelineRequest\x1a-.neuropipe.executor.v1.DeployPipelineResponse\x12s\n" +
	"\x10UndeployPipeline\x12..neuropipe.executor.v1.UndeployPipelineRequest\x1a/.neuropipe.executor.v1.UndeployPipelineResponse\x12g\n" +
	"\fListDeployed\x12*.neuropipe.executor.v1.ListDeployedRequest\x1a+.neuropipe.executor.v1.ListDeployedResponse\x12[\n" +
	"\bStartRun\x12&.neuropipe.executor.v1.StartRunRequest\x1a'.neuropipe.executor.v1.StartRunResponse\x12^\n" +
	"\tCancelRun\x12'.neuropipe.executor.v1.CancelRunRequest\x1a(.neuropipe.executor.v1.CancelRunResponse\x12R\n" +
	"\x06GetRun\x12$.neuropipe.executor.v1.GetRunRequest\x1a\".neuropipe.executor.v1.RunSnapshot\x12[\n" +
	"\bListRuns\x12&.neuropipe.executor.v1.ListRunsRequest\x1a'.neuropipe.executor.v1.ListRunsResponse\x12c\n" +
	"\fStreamEvents\x12*.neuropipe.executor.v1.StreamEventsRequest\x1a%.neuropipe.executor.v1.ExecutionEvent0\x01\x12T\n" +
	"\x06Tunnel\x12\".neuropipe.executor.v1.TunnelFrame\x1a\".neuropipe.executor.v1.TunnelFrame(\x010\x01BKZIgithub.com/FlameInTheDark/neuropipe/internal/proto/executor/v1;executorv1b\x06proto3"

var (
	file_executor_v1_executor_proto_rawDescOnce sync.Once
	file_executor_v1_executor_proto_rawDescData []byte
)

func file_executor_v1_executor_proto_rawDescGZIP() []byte {
	file_executor_v1_executor_proto_rawDescOnce.Do(func() {
		file_executor_v1_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_executor_v1_executor_proto_rawDesc), len(file_executor_v1_executor_proto_rawDesc)))
	})
	return file_executor_v1_executor_proto_rawDescData
}

var file_executor_v1_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_executor_v1_executor_proto_goTypes = []any{
	(*StatusRequest)(nil),            // 0: neuropipe.executor.v1.StatusRequest
	(*ExecutorStatus)(nil),           // 1: neuropipe.executor.v1.ExecutorStatus
	(*GetConfigRequest)(nil),         // 2: neuropipe.executor.v1.GetConfigRequest
	(*UpdateConfigRequest)(nil),      // 3: neuropipe.executor.v1.UpdateConfigRequest
	(*ExecutorConfig)(nil),           // 4: neuropipe.executor.v1.ExecutorConfig
	(*ExecutorProvider)(nil),         // 5: neuropipe.executor.v1.ExecutorProvider
	(*DeployPipelineRequest)(nil),    // 6: neuropipe.executor.v1.DeployPipelineRequest
	(*DeployPipelineResponse)(nil),   // 7: neuropipe.executor.v1.DeployPipelineResponse
	(*DeployedTrigger)(nil),          // 8: neuropipe.executor.v1.DeployedTrigger
	(*UndeployPipelineRequest)(nil),  // 9: neuropipe.executor.v1.UndeployPipelineRequest
	(*UndeployPipelineResponse)(nil), // 10: neuropipe.executor.v1.UndeployPipelineResponse
	(*ListDeployedRequest)(nil),      // 11: neuropipe.executor.v1.ListDeployedRequest
	(*ListDeployedResponse)(nil),     // 12: neuropipe.executor.v1.ListDeployedResponse
	(*DeployedPipelineInfo)(nil),     // 13: neuropipe.executor.v1.DeployedPipelineInfo
	(*StartRunRequest)(nil),          // 14: neuropipe.executor.v1.StartRunRequest
	(*StartRunResponse)(nil),         // 15: neuropipe.executor.v1.StartRunResponse
	(*CancelRunRequest)(nil),         // 16: neuropipe.executor.v1.CancelRunRequest
	(*CancelRunResponse)(nil),        // 17: neuropipe.executor.v1.CancelRunResponse
	(*GetRunRequest)(nil),            // 18: neuropipe.executor.v1.GetRunRequest
	(*ListRunsRequest)(nil),          // 19: neuropipe.executor.v1.ListRunsRequest
	(*ListRunsResponse)(nil),         // 20: neuropipe.executor.v1.ListRunsResponse
	(*StreamEventsRequest)(nil),      // 21: neuropipe.executor.v1.StreamEventsRequest
	(*ExecutionEvent)(nil),           // 22: neuropipe.executor.v1.ExecutionEvent
	(*RunSnapshot)(nil),              // 23: neuropipe.executor.v1.RunSnapshot
	(*NodeRun)(nil),                  // 24: neuropipe.executor.v1.NodeRun
	(*TunnelFrame)(nil),              // 25: neuropipe.executor.v1.TunnelFrame
	(*HostCall)(nil),                 // 26: neuropipe.executor.v1.HostCall
	(*HostResponse)(nil),             // 27: neuropipe.executor.v1.HostResponse
	(*timestamppb.Timestamp)(nil),    // 28: google.protobuf.Timestamp
}
var file_executor_v1_executor_proto_depIdxs = []int32{
	4,  // 0: neuropipe.executor.v1.UpdateConfigRequest.config:type_name -> neuropipe.executor.v1.ExecutorConfig
	5,  // 1: neuropipe.executor.v1.ExecutorConfig.providers:type_name -> neuropipe.executor.v1.ExecutorProvider
	8,  // 2: neuropipe.executor.v1.DeployPipelineRequest.triggers:type_name -> neuropipe.executor.v1.DeployedTrigger
	13, // 3: neuropipe.executor.v1.ListDeployedResponse.pipelines:type_name -> neuropipe.executor.v1.DeployedPipelineInfo
	28, // 4: neuropipe.executor.v1.DeployedPipelineInfo.deployed_at:type_name -> google.protobuf.Timestamp
	23, // 5: neuropipe.executor.v1.ListRunsResponse.runs:type_name -> neuropipe.executor.v1.RunSnapshot
	23, // 6: neuropipe.executor.v1.ExecutionEvent.run:type_name -> neuropipe.executor.v1.RunSnapshot
	28, // 7: neuropipe.executor.v1.RunSnapshot.started_at:type_name -> google.protobuf.Timestamp
	28, // 8: neuropipe.executor.v1.RunSnapshot.finished_at:type_name -> google.protobuf.Timestamp
	24, // 9: neuropipe.executor.v1.RunSnapshot.node_runs:type_name -> neuropipe.executor.v1.NodeRun
	28, // 10: neuropipe.executor.v1.RunSnapshot.run_started_at:type_name -> google.protobuf.Timestamp
	28, // 11: neuropipe.executor.v1.NodeRun.started_at:type_name -> google.protobuf.Timestamp
	28, // 12: neuropipe.executor.v1.NodeRun.finished_at:type_name -> google.protobuf.Timestamp
	26, // 13: neuropipe.executor.v1.TunnelFrame.call:type_name -> neuropipe.executor.v1.HostCall
	27, // 14: neuropipe.executor.v1.TunnelFrame.response:type_name -> neuropipe.executor.v1.HostResponse
	0,  // 15: neuropipe.executor.v1.Executor.GetStatus:input_type -> neuropipe.executor.v1.StatusRequest
	2,  // 16: neuropipe.executor.v1.Executor.GetConfig:input_type -> neuropipe.executor.v1.GetConfigRequest
	3,  // 17: neuropipe.executor.v1.Executor.UpdateConfig:input_type -> neuropipe.executor.v1.UpdateConfigRequest
	6,  // 18: neuropipe.executor.v1.Executor.DeployPipeline:input_type -> neuropipe.executor.v1.DeployPipelineRequest
	9,  // 19: neuropipe.executor.v1.Executor.UndeployPipeline:input_type -> neuropipe.executor.v1.UndeployPipelineRequest
	11, // 20: neuropipe.executor.v1.Executor.ListDeployed:input_type -> neuropipe.executor.v1.ListDeployedRequest
	14, // 21: neuropipe.executor.v1.Executor.StartRun:input_type -> neuropipe.executor.v1.StartRunRequest
	16, // 22: neuropipe.executor.v1.Executor.CancelRun:input_type -> neuropipe.executor.v1.CancelRunRequest
	18, // 23: neuropipe.executor.v1.Executor.GetRun:input_type -> neuropipe.executor.v1.GetRunRequest
	19, // 24: neuropipe.executor.v1.Executor.ListRuns:input_type -> neuropipe.executor.v1.ListRunsRequest
	21, // 25: neuropipe.executor.v1.Executor.StreamEvents:input_type -> neuropipe.executor.v1.StreamEventsRequest
	25, // 26: neuropipe.executor.v1.Executor.Tunnel:input_type -> neuropipe.executor.v1.TunnelFrame
	1,  // 27: neuropipe.executor.v1.Executor.GetStatus:output_type -> neuropipe.executor.v1.ExecutorStatus
	4,  // 28: neuropipe.executor.v1.Executor.GetConfig:output_type -> neuropipe.executor.v1.ExecutorConfig
	4,  // 29: neuropipe.executor.v1.Executor.UpdateConfig:output_type -> neuropipe.executor.v1.ExecutorConfig
	7,  // 30: neuropipe.executor.v1.Executor.DeployPipeline:output_type -> neuropipe.executor.v1.DeployPipelineResponse
	10, // 31: neuropipe.executor.v1.Executor.UndeployPipeline:output_type -> neuropipe.executor.v1.UndeployPipelineResponse
	12, // 32: neuropipe.executor.v1.Executor.ListDeployed:output_type -> neuropipe.executor.v1.ListDeployedResponse
	15, // 33: neuropipe.executor.v1.Executor.StartRun:output_type -> neuropipe.executor.v1.StartRunResponse
	17, // 34: neuropipe.executor.v1.Executor.CancelRun:output_type -> neuropipe.executor.v1.CancelRunResponse
	23, // 35: neuropipe.executor.v1.Executor.GetRun:output_type -> neuropipe.executor.v1.RunSnapshot
	20, // 36: neuropipe.executor.v1.Executor.ListRuns:output_type -> neuropipe.executor.v1.ListRunsResponse
	22, // 37: neuropipe.executor.v1.Executor.StreamEvents:output_type -> neuropipe.executor.v1.ExecutionEvent
	25, // 38: neuropipe.executor.v1.Executor.Tunnel:output_type -> neuropipe.executor.v1.TunnelFrame
	27, // [27:39] is the sub-list for method output_type
	15, // [15:27] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_executor_v1_executor_proto_init() }
func file_executor_v1_executor_proto_init() {
	if File_executor_v1_executor_proto != nil {
		return
	}
	file_executor_v1_executor_proto_msgTypes[25].OneofWrappers = []any{
		(*TunnelFrame_Call)(nil),
		(*TunnelFrame_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_executor_v1_executor_proto_rawDesc), len(file_executor_v1_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_executor_v1_executor_proto_goTypes,
		DependencyIndexes: file_executor_v1_executor_proto_depIdxs,
		MessageInfos:      file_executor_v1_executor_proto_msgTypes,
	}.Build()
	File_executor_v1_executor_proto = out.File
	file_executor_v1_executor_proto_goTypes = nil
	file_executor_v1_executor_proto_depIdxs = nil
}
