// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {app} from '../models';
import {llm} from '../models';
import {security} from '../models';
import {context} from '../models';

export function AddTwitchManualIdentity(arg1:domain.TwitchManualIdentityRequest):Promise<domain.TwitchIdentity>;

export function CancelChatRun(arg1:string):Promise<void>;

export function CancelTwitchDeviceAuthorization(arg1:string):Promise<void>;

export function ChooseContentDirectory():Promise<string>;

export function ClearMetrics():Promise<void>;

export function ConfigureTrayMenu(arg1:app.TrayMenuLabels):Promise<void>;

export function CreateChatConversation(arg1:domain.ChatMode,arg2:string):Promise<domain.ChatConversation>;

export function CreateFunction(arg1:domain.CreateFunctionRequest):Promise<domain.CustomFunction>;

export function CreatePipeline(arg1:string):Promise<domain.Pipeline>;

export function DeleteChatConversation(arg1:string):Promise<void>;

export function DeleteFunction(arg1:string):Promise<void>;

export function DeleteInstalledLlamaModel(arg1:string):Promise<void>;

export function DeletePipeline(arg1:string):Promise<void>;

export function DeleteReport(arg1:string):Promise<void>;

export function DeleteSecret(arg1:string):Promise<void>;

export function DuplicatePipeline(arg1:string):Promise<domain.Pipeline>;

export function GetAPIStatus():Promise<domain.APIStatus>;

export function GetDocumentation(arg1:string,arg2:string):Promise<domain.DocumentationDocument>;

export function GetDocumentationForNode(arg1:string):Promise<domain.DocumentationReference>;

export function GetExecution(arg1:string):Promise<domain.Execution>;

export function GetFunction(arg1:string):Promise<domain.CustomFunction>;

export function GetInstallProgress(arg1:string):Promise<domain.InstallProgress>;

export function GetLlamaModelDetail(arg1:string):Promise<domain.ModelDetail>;

export function GetLlamaRuntimeCatalogStatus():Promise<domain.LlamaRuntimeCatalogStatus>;

export function GetLlamaRuntimeStatus():Promise<domain.LlamaRuntimeStatus>;

export function GetMetricsOverview(arg1:domain.MetricsFilter):Promise<domain.MetricsOverview>;

export function GetPipeline(arg1:string):Promise<domain.Pipeline>;

export function GetRequiredCapabilities(arg1:string):Promise<Array<domain.Capability>>;

export function GetSettings():Promise<domain.Settings>;

export function GetTwitchStatus():Promise<domain.TwitchStatus>;

export function GetUpdateAvailability():Promise<domain.UpdateAvailability>;

export function GrantCapability(arg1:domain.PermissionGrant):Promise<void>;

export function HandleWebhook(arg1:string,arg2:Array<number>,arg3:string):Promise<domain.Execution>;

export function InstallLlamaModel(arg1:domain.ModelInstallRequest):Promise<domain.LocalModel>;

export function InstallLlamaRuntime(arg1:domain.LlamaRuntimeInstallRequest):Promise<domain.LlamaRuntimeCatalogStatus>;

export function ListAllTriggers():Promise<Array<domain.TriggerBinding>>;

export function ListChatConversations():Promise<Array<domain.ChatConversation>>;

export function ListChatMessages(arg1:string):Promise<Array<domain.ChatMessage>>;

export function ListChatPipelines():Promise<Array<domain.ChatPipeline>>;

export function ListChatRunEvents(arg1:string):Promise<Array<domain.ChatRunEvent>>;

export function ListChatRuns(arg1:string):Promise<Array<domain.ChatRun>>;

export function ListDocumentation(arg1:string):Promise<Array<domain.DocumentationEntry>>;

export function ListExecutions(arg1:string):Promise<Array<domain.Execution>>;

export function ListFunctions():Promise<Array<domain.FunctionSummary>>;

export function ListInstalledLlamaModels():Promise<Array<domain.LocalModel>>;

export function ListLlamaModelFiles(arg1:string):Promise<Array<domain.ModelFile>>;

export function ListLlamaRuntimeReleases():Promise<Array<domain.LlamaRuntimeRelease>>;

export function ListNodeDefinitions():Promise<Array<domain.NodeDefinition>>;

export function ListPendingChatApprovals(arg1:string):Promise<Array<domain.ChatApproval>>;

export function ListPipelines():Promise<Array<domain.PipelineSummary>>;

export function ListPlugins():Promise<Array<domain.PluginStatus>>;

export function ListProviderModels(arg1:string):Promise<Array<llm.ModelInfo>>;

export function ListRecentExecutions(arg1:number):Promise<Array<domain.Execution>>;

export function ListReports():Promise<Array<domain.Report>>;

export function ListSchedules():Promise<Array<domain.TriggerBinding>>;

export function ListSecrets():Promise<Array<security.SecretMetadata>>;

export function ListTriggerButtons():Promise<Array<domain.TriggerBinding>>;

export function ListTwitchEventCatalog():Promise<Array<domain.TwitchEventDescriptor>>;

export function ListTwitchTriggers():Promise<Array<domain.TriggerBinding>>;

export function OpenUpdateRelease():Promise<void>;

export function PublishFunction(arg1:domain.CustomFunction):Promise<domain.CustomFunction>;

export function PublishPipeline(arg1:domain.Pipeline):Promise<domain.Pipeline>;

export function RecordHTTPMetric(arg1:domain.MetricActivityEvent):Promise<void>;

export function RediscoverPlugins():Promise<Array<domain.PluginStatus>>;

export function RemoveTwitchIdentity(arg1:string):Promise<void>;

export function ResolveChatApproval(arg1:string,arg2:boolean):Promise<void>;

export function ResolveNodeDefinition(arg1:domain.FlowNode):Promise<domain.NodeDefinition>;

export function RotateAPIToken():Promise<string>;

export function RunPipelineDraft(arg1:string,arg2:string):Promise<domain.Execution>;

export function RunTrigger(arg1:string):Promise<domain.Execution>;

export function SaveChatConversation(arg1:domain.ChatConversation):Promise<domain.ChatConversation>;

export function SaveFunction(arg1:domain.CustomFunction):Promise<domain.CustomFunction>;

export function SavePipeline(arg1:domain.Pipeline):Promise<domain.Pipeline>;

export function SaveSecret(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:domain.Settings):Promise<void>;

export function SearchDocumentation(arg1:string,arg2:string):Promise<Array<domain.DocumentationSearchResult>>;

export function SearchLlamaModels(arg1:domain.ModelSearchRequest):Promise<Array<domain.ModelSearchResult>>;

export function SelectInstalledLlamaModel(arg1:string):Promise<void>;

export function SendChatMessage(arg1:string,arg2:string):Promise<domain.ChatRun>;

export function SetScheduleEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetTwitchTriggerEnabled(arg1:string,arg2:boolean):Promise<void>;

export function ShouldHideToTrayOnClose():Promise<boolean>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartLlamaRuntime():Promise<domain.LlamaRuntimeStatus>;

export function StartPublishedPipeline(arg1:string,arg2:string,arg3:Record<string, any>):Promise<domain.Execution>;

export function StartTwitchDeviceAuthorization(arg1:domain.TwitchDeviceAuthorizationRequest):Promise<domain.TwitchDeviceAuthorization>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopLlamaRuntime():Promise<domain.LlamaRuntimeStatus>;

export function TrustPipelineRevision(arg1:string,arg2:number):Promise<void>;

export function TrustTwitchTrigger(arg1:string):Promise<void>;

export function ValidateJavaScript(arg1:string):Promise<void>;
