// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTwitchManualIdentity(arg1) {
  return window['go']['app']['Desktop']['AddTwitchManualIdentity'](arg1);
}

export function CancelChatRun(arg1) {
  return window['go']['app']['Desktop']['CancelChatRun'](arg1);
}

export function CancelTwitchDeviceAuthorization(arg1) {
  return window['go']['app']['Desktop']['CancelTwitchDeviceAuthorization'](arg1);
}

export function ChooseContentDirectory() {
  return window['go']['app']['Desktop']['ChooseContentDirectory']();
}

export function ClearMetrics() {
  return window['go']['app']['Desktop']['ClearMetrics']();
}

export function ConfigureTrayMenu(arg1) {
  return window['go']['app']['Desktop']['ConfigureTrayMenu'](arg1);
}

export function CreateChatConversation(arg1, arg2) {
  return window['go']['app']['Desktop']['CreateChatConversation'](arg1, arg2);
}

export function CreateFunction(arg1) {
  return window['go']['app']['Desktop']['CreateFunction'](arg1);
}

export function CreateGlobalVariable(arg1) {
  return window['go']['app']['Desktop']['CreateGlobalVariable'](arg1);
}

export function CreatePipeline(arg1) {
  return window['go']['app']['Desktop']['CreatePipeline'](arg1);
}

export function DeleteChatConversation(arg1) {
  return window['go']['app']['Desktop']['DeleteChatConversation'](arg1);
}

export function DeleteFunction(arg1) {
  return window['go']['app']['Desktop']['DeleteFunction'](arg1);
}

export function DeleteGlobalVariable(arg1) {
  return window['go']['app']['Desktop']['DeleteGlobalVariable'](arg1);
}

export function DeleteInstalledLlamaModel(arg1) {
  return window['go']['app']['Desktop']['DeleteInstalledLlamaModel'](arg1);
}

export function DeletePipeline(arg1) {
  return window['go']['app']['Desktop']['DeletePipeline'](arg1);
}

export function DeleteReport(arg1) {
  return window['go']['app']['Desktop']['DeleteReport'](arg1);
}

export function DeleteSecret(arg1) {
  return window['go']['app']['Desktop']['DeleteSecret'](arg1);
}

export function DuplicatePipeline(arg1) {
  return window['go']['app']['Desktop']['DuplicatePipeline'](arg1);
}

export function GetAPIStatus() {
  return window['go']['app']['Desktop']['GetAPIStatus']();
}

export function GetDocumentation(arg1, arg2) {
  return window['go']['app']['Desktop']['GetDocumentation'](arg1, arg2);
}

export function GetDocumentationForNode(arg1) {
  return window['go']['app']['Desktop']['GetDocumentationForNode'](arg1);
}

export function GetExecution(arg1) {
  return window['go']['app']['Desktop']['GetExecution'](arg1);
}

export function GetFunction(arg1) {
  return window['go']['app']['Desktop']['GetFunction'](arg1);
}

export function GetInstallProgress(arg1) {
  return window['go']['app']['Desktop']['GetInstallProgress'](arg1);
}

export function GetLlamaModelDetail(arg1) {
  return window['go']['app']['Desktop']['GetLlamaModelDetail'](arg1);
}

export function GetLlamaRuntimeCatalogStatus() {
  return window['go']['app']['Desktop']['GetLlamaRuntimeCatalogStatus']();
}

export function GetLlamaRuntimeStatus() {
  return window['go']['app']['Desktop']['GetLlamaRuntimeStatus']();
}

export function GetMetricsOverview(arg1) {
  return window['go']['app']['Desktop']['GetMetricsOverview'](arg1);
}

export function GetPipeline(arg1) {
  return window['go']['app']['Desktop']['GetPipeline'](arg1);
}

export function GetRequiredCapabilities(arg1) {
  return window['go']['app']['Desktop']['GetRequiredCapabilities'](arg1);
}

export function GetSettings() {
  return window['go']['app']['Desktop']['GetSettings']();
}

export function GetTwitchStatus() {
  return window['go']['app']['Desktop']['GetTwitchStatus']();
}

export function GetUpdateAvailability() {
  return window['go']['app']['Desktop']['GetUpdateAvailability']();
}

export function GrantCapability(arg1) {
  return window['go']['app']['Desktop']['GrantCapability'](arg1);
}

export function HandleWebhook(arg1, arg2, arg3) {
  return window['go']['app']['Desktop']['HandleWebhook'](arg1, arg2, arg3);
}

export function InstallLlamaModel(arg1) {
  return window['go']['app']['Desktop']['InstallLlamaModel'](arg1);
}

export function InstallLlamaRuntime(arg1) {
  return window['go']['app']['Desktop']['InstallLlamaRuntime'](arg1);
}

export function ListAllTriggers() {
  return window['go']['app']['Desktop']['ListAllTriggers']();
}

export function ListChatConversations() {
  return window['go']['app']['Desktop']['ListChatConversations']();
}

export function ListChatMessages(arg1) {
  return window['go']['app']['Desktop']['ListChatMessages'](arg1);
}

export function ListChatPipelines() {
  return window['go']['app']['Desktop']['ListChatPipelines']();
}

export function ListChatRunEvents(arg1) {
  return window['go']['app']['Desktop']['ListChatRunEvents'](arg1);
}

export function ListChatRuns(arg1) {
  return window['go']['app']['Desktop']['ListChatRuns'](arg1);
}

export function ListDocumentation(arg1) {
  return window['go']['app']['Desktop']['ListDocumentation'](arg1);
}

export function ListExecutions(arg1) {
  return window['go']['app']['Desktop']['ListExecutions'](arg1);
}

export function ListFunctions() {
  return window['go']['app']['Desktop']['ListFunctions']();
}

export function ListGlobalVariables() {
  return window['go']['app']['Desktop']['ListGlobalVariables']();
}

export function ListInstalledLlamaModels() {
  return window['go']['app']['Desktop']['ListInstalledLlamaModels']();
}

export function ListLlamaModelFiles(arg1) {
  return window['go']['app']['Desktop']['ListLlamaModelFiles'](arg1);
}

export function ListLlamaRuntimeReleases() {
  return window['go']['app']['Desktop']['ListLlamaRuntimeReleases']();
}

export function ListNodeDefinitions() {
  return window['go']['app']['Desktop']['ListNodeDefinitions']();
}

export function ListPendingChatApprovals(arg1) {
  return window['go']['app']['Desktop']['ListPendingChatApprovals'](arg1);
}

export function ListPipelines() {
  return window['go']['app']['Desktop']['ListPipelines']();
}

export function ListPlugins() {
  return window['go']['app']['Desktop']['ListPlugins']();
}

export function ListProviderModels(arg1) {
  return window['go']['app']['Desktop']['ListProviderModels'](arg1);
}

export function ListRecentExecutions(arg1) {
  return window['go']['app']['Desktop']['ListRecentExecutions'](arg1);
}

export function ListReports() {
  return window['go']['app']['Desktop']['ListReports']();
}

export function ListSchedules() {
  return window['go']['app']['Desktop']['ListSchedules']();
}

export function ListSecrets() {
  return window['go']['app']['Desktop']['ListSecrets']();
}

export function ListTriggerButtons() {
  return window['go']['app']['Desktop']['ListTriggerButtons']();
}

export function ListTwitchEventCatalog() {
  return window['go']['app']['Desktop']['ListTwitchEventCatalog']();
}

export function ListTwitchTriggers() {
  return window['go']['app']['Desktop']['ListTwitchTriggers']();
}

export function OpenUpdateRelease() {
  return window['go']['app']['Desktop']['OpenUpdateRelease']();
}

export function PublishFunction(arg1) {
  return window['go']['app']['Desktop']['PublishFunction'](arg1);
}

export function PublishPipeline(arg1) {
  return window['go']['app']['Desktop']['PublishPipeline'](arg1);
}

export function RecordHTTPMetric(arg1) {
  return window['go']['app']['Desktop']['RecordHTTPMetric'](arg1);
}

export function RediscoverPlugins() {
  return window['go']['app']['Desktop']['RediscoverPlugins']();
}

export function RemoveTwitchIdentity(arg1) {
  return window['go']['app']['Desktop']['RemoveTwitchIdentity'](arg1);
}

export function ResolveChatApproval(arg1, arg2) {
  return window['go']['app']['Desktop']['ResolveChatApproval'](arg1, arg2);
}

export function ResolveNodeDefinition(arg1) {
  return window['go']['app']['Desktop']['ResolveNodeDefinition'](arg1);
}

export function RotateAPIToken() {
  return window['go']['app']['Desktop']['RotateAPIToken']();
}

export function RunPipelineDraft(arg1, arg2) {
  return window['go']['app']['Desktop']['RunPipelineDraft'](arg1, arg2);
}

export function RunTrigger(arg1) {
  return window['go']['app']['Desktop']['RunTrigger'](arg1);
}

export function SaveChatConversation(arg1) {
  return window['go']['app']['Desktop']['SaveChatConversation'](arg1);
}

export function SaveFunction(arg1) {
  return window['go']['app']['Desktop']['SaveFunction'](arg1);
}

export function SavePipeline(arg1) {
  return window['go']['app']['Desktop']['SavePipeline'](arg1);
}

export function SaveSecret(arg1, arg2) {
  return window['go']['app']['Desktop']['SaveSecret'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['app']['Desktop']['SaveSettings'](arg1);
}

export function SearchDocumentation(arg1, arg2) {
  return window['go']['app']['Desktop']['SearchDocumentation'](arg1, arg2);
}

export function SearchLlamaModels(arg1) {
  return window['go']['app']['Desktop']['SearchLlamaModels'](arg1);
}

export function SelectInstalledLlamaModel(arg1) {
  return window['go']['app']['Desktop']['SelectInstalledLlamaModel'](arg1);
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['app']['Desktop']['SendChatMessage'](arg1, arg2);
}

export function SetScheduleEnabled(arg1, arg2) {
  return window['go']['app']['Desktop']['SetScheduleEnabled'](arg1, arg2);
}

export function SetTwitchTriggerEnabled(arg1, arg2) {
  return window['go']['app']['Desktop']['SetTwitchTriggerEnabled'](arg1, arg2);
}

export function ShouldHideToTrayOnClose() {
  return window['go']['app']['Desktop']['ShouldHideToTrayOnClose']();
}

export function Shutdown(arg1) {
  return window['go']['app']['Desktop']['Shutdown'](arg1);
}

export function StartLlamaRuntime() {
  return window['go']['app']['Desktop']['StartLlamaRuntime']();
}

export function StartPublishedPipeline(arg1, arg2, arg3) {
  return window['go']['app']['Desktop']['StartPublishedPipeline'](arg1, arg2, arg3);
}

export function StartTwitchDeviceAuthorization(arg1) {
  return window['go']['app']['Desktop']['StartTwitchDeviceAuthorization'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['Desktop']['Startup'](arg1);
}

export function StopLlamaRuntime() {
  return window['go']['app']['Desktop']['StopLlamaRuntime']();
}

export function TrustPipelineRevision(arg1, arg2) {
  return window['go']['app']['Desktop']['TrustPipelineRevision'](arg1, arg2);
}

export function TrustTwitchTrigger(arg1) {
  return window['go']['app']['Desktop']['TrustTwitchTrigger'](arg1);
}

export function UpdateGlobalVariable(arg1) {
  return window['go']['app']['Desktop']['UpdateGlobalVariable'](arg1);
}

export function ValidateJavaScript(arg1) {
  return window['go']['app']['Desktop']['ValidateJavaScript'](arg1);
}
