import type { APIStatus, Capability, ChatApproval, ChatConversation, ChatMessage, ChatMode, ChatPipeline, ChatRun, ChatRunEvent, CreateFunctionRequest, CustomFunction, DocumentationDocument, DocumentationEntry, DocumentationReference, DocumentationSearchResult, Execution, FunctionSummary, InstallProgress, LlamaRuntimeCatalogStatus, LlamaRuntimeInstallRequest, LlamaRuntimeRelease, LlamaRuntimeStatus, LocalModel, MetricsFilter, MetricsOverview, ModelDetail, ModelInstallRequest, ModelSearchRequest, ModelSearchResult, NodeDefinition, Pipeline, PipelineSummary, PluginStatus, Report, SecretMetadata, Settings, TrayMenuLabels, TriggerBinding, UpdateAvailability } from '@/lib/types'
import i18n from '@/i18n'

async function call<T>(method: string, ...args: unknown[]): Promise<T> {
  const binding = window.go?.app?.Desktop?.[method]
  if (!binding) {
    throw new Error(i18n.t('app.unavailable'))
  }
  return binding(...args) as Promise<T>
}

export const desktop = {
	getUpdateAvailability: () => call<UpdateAvailability>('GetUpdateAvailability'),
	openUpdateRelease: () => call<void>('OpenUpdateRelease'),
  listPipelines: () => call<PipelineSummary[]>('ListPipelines'),
  createPipeline: (name: string) => call<Pipeline>('CreatePipeline', name),
  deletePipeline: (id: string) => call<void>('DeletePipeline', id),
  duplicatePipeline: (id: string) => call<Pipeline>('DuplicatePipeline', id),
  getPipeline: (id: string) => call<Pipeline>('GetPipeline', id),
  savePipeline: (pipeline: Pipeline) => call<Pipeline>('SavePipeline', pipeline),
  publishPipeline: (pipeline: Pipeline) => call<Pipeline>('PublishPipeline', pipeline),
  listNodes: () => call<NodeDefinition[]>('ListNodeDefinitions'),
  validateJavaScript: (code: string) => call<void>('ValidateJavaScript', code),
  listDocumentation: (language: string) => call<DocumentationEntry[]>('ListDocumentation', language),
  getDocumentation: (language: string, id: string) => call<DocumentationDocument>('GetDocumentation', language, id),
  searchDocumentation: (language: string, query: string) => call<DocumentationSearchResult[]>('SearchDocumentation', language, query),
  getDocumentationForNode: (nodeType: string) => call<DocumentationReference>('GetDocumentationForNode', nodeType),
  listFunctions: () => call<FunctionSummary[]>('ListFunctions'),
  createFunction: (request: CreateFunctionRequest) => call<CustomFunction>('CreateFunction', request),
  getFunction: (id: string) => call<CustomFunction>('GetFunction', id),
  saveFunction: (item: CustomFunction) => call<CustomFunction>('SaveFunction', item),
  publishFunction: (item: CustomFunction) => call<CustomFunction>('PublishFunction', item),
  deleteFunction: (id: string) => call<void>('DeleteFunction', id),
  listButtons: () => call<TriggerBinding[]>('ListTriggerButtons'),
  listSchedules: () => call<TriggerBinding[]>('ListSchedules'),
  setScheduleEnabled: (id: string, enabled: boolean) => call<void>('SetScheduleEnabled', id, enabled),
  runTrigger: (id: string) => call<Execution>('RunTrigger', id),
  runPipelineDraft: (pipelineId: string, triggerNodeId: string) => call<Execution>('RunPipelineDraft', pipelineId, triggerNodeId),
  listExecutions: (pipelineId: string) => call<Execution[]>('ListExecutions', pipelineId),
  getExecution: (id: string) => call<Execution>('GetExecution', id),
  getMetricsOverview: (filter: MetricsFilter) => call<MetricsOverview>('GetMetricsOverview', filter),
  clearMetrics: () => call<void>('ClearMetrics'),
  listReports: () => call<Report[]>('ListReports'),
  deleteReport: (id: string) => call<void>('DeleteReport', id),
  listChatConversations: () => call<ChatConversation[]>('ListChatConversations'),
  listChatPipelines: () => call<ChatPipeline[]>('ListChatPipelines'),
  createChatConversation: (mode: ChatMode, bindingId = '') => call<ChatConversation>('CreateChatConversation', mode, bindingId),
  saveChatConversation: (conversation: ChatConversation) => call<ChatConversation>('SaveChatConversation', conversation),
  deleteChatConversation: (id: string) => call<void>('DeleteChatConversation', id),
  listChatMessages: (conversationId: string) => call<ChatMessage[]>('ListChatMessages', conversationId),
  listChatRuns: (conversationId: string) => call<ChatRun[]>('ListChatRuns', conversationId),
  listChatRunEvents: (chatRunId: string) => call<ChatRunEvent[]>('ListChatRunEvents', chatRunId),
  sendChatMessage: (conversationId: string, text: string) => call<ChatRun>('SendChatMessage', conversationId, text),
  cancelChatRun: (id: string) => call<void>('CancelChatRun', id),
  listPendingChatApprovals: (conversationId: string) => call<ChatApproval[]>('ListPendingChatApprovals', conversationId),
  resolveChatApproval: (id: string, approved: boolean) => call<void>('ResolveChatApproval', id, approved),
  getCapabilities: (pipelineId: string) => call<Capability[]>('GetRequiredCapabilities', pipelineId),
  trustRevision: (pipelineId: string, revision: number) => call<void>('TrustPipelineRevision', pipelineId, revision),
  getSettings: () => call<Settings>('GetSettings'),
  saveSettings: (settings: Settings) => call<void>('SaveSettings', settings),
	configureTrayMenu: (labels: TrayMenuLabels) => call<void>('ConfigureTrayMenu', labels),
  chooseContentDirectory: () => call<string>('ChooseContentDirectory'),
  getLlamaRuntimeStatus: () => call<LlamaRuntimeStatus>('GetLlamaRuntimeStatus'),
  startLlamaRuntime: () => call<LlamaRuntimeStatus>('StartLlamaRuntime'),
  stopLlamaRuntime: () => call<LlamaRuntimeStatus>('StopLlamaRuntime'),
  listLlamaRuntimeReleases: () => call<LlamaRuntimeRelease[]>('ListLlamaRuntimeReleases'),
  getLlamaRuntimeCatalogStatus: () => call<LlamaRuntimeCatalogStatus>('GetLlamaRuntimeCatalogStatus'),
  getInstallProgress: (kind: InstallProgress['kind']) => call<InstallProgress>('GetInstallProgress', kind),
  installLlamaRuntime: (request: LlamaRuntimeInstallRequest) => call<LlamaRuntimeCatalogStatus>('InstallLlamaRuntime', request),
  searchLlamaModels: (request: ModelSearchRequest) => call<ModelSearchResult[]>('SearchLlamaModels', request),
  getLlamaModelDetail: (repository: string) => call<ModelDetail>('GetLlamaModelDetail', repository),
  listInstalledLlamaModels: () => call<LocalModel[]>('ListInstalledLlamaModels'),
  installLlamaModel: (request: ModelInstallRequest) => call<LocalModel>('InstallLlamaModel', request),
  selectInstalledLlamaModel: (path: string) => call<void>('SelectInstalledLlamaModel', path),
  deleteInstalledLlamaModel: (path: string) => call<void>('DeleteInstalledLlamaModel', path),
  getAPIStatus: () => call<APIStatus>('GetAPIStatus'),
  rotateAPIToken: () => call<string>('RotateAPIToken'),
  listSecrets: () => call<SecretMetadata[]>('ListSecrets'),
  saveSecret: (name: string, value: string) => call<void>('SaveSecret', name, value),
  deleteSecret: (name: string) => call<void>('DeleteSecret', name),
  listPlugins: () => call<PluginStatus[]>('ListPlugins'),
  rediscoverPlugins: () => call<PluginStatus[]>('RediscoverPlugins'),
}
